CREATE TABLE dbo.[Node]
(
	NodeID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	IPAddress NVARCHAR(12) NOT NULL,
	NodeName NVARCHAR(128) NOT NULL DEFAULT '',
	LocationName NVARCHAR(128) NOT NULL DEFAULT ''
)