CREATE TABLE dbo.NodeData
(
	NodeID INT PRIMARY KEY NOT NULL,
	Battery FLOAT NOT NULL DEFAULT 0.0,
	Temperature FLOAT NOT NULL DEFAULT 0.0,
	Flow FLOAT NOT NULL DEFAULT 0.0,
	[Status] NVARCHAR(128) NOT NULL DEFAULT 'IDLE',
	[TimeStamp] DATETIME NOT NULL DEFAULT GETDATE(),

	CONSTRAINT FK_NodeID FOREIGN KEY (NodeID) REFERENCES Node (NodeID) ON DELETE CASCADE
)